In [1]:
import numpy as np

<h3>A numpy array</h3>

In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


<h3>Different attributes of numpy array</h3>

In [26]:
print(a.shape) #dimensions of the array
print(a.size) #number of elements in the array
print(a.dtype) #data type of the array
print(a.itemsize) #item size in bytes

(3,)
3
int32
4


<h3>Changing the data type</h3>

In [27]:
a.dtype = 'int16'
print(a.dtype)

int16


<h3>Creating a standard array</h3>

In [28]:
b = np.zeros((3,3), 'int8') #matrix of zeros of given shape
c = np.ones((3,3),'int8') #matrix of ones of given shape
d = np.full(b.shape,90) #matrix of given dimentions with only one element
i = np.identity(3,'int8') #identity matrix of given shape
seq = np.arange(9) #matrix of whole numbers of given size

print(b)
print(c)
print(d)
print(i)
print(seq)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[90 90 90]
 [90 90 90]
 [90 90 90]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[0 1 2 3 4 5 6 7 8]


<h3>Accessing elements form an array</h3>

In [29]:
seq[2:6] #similar to that in a list

array([2, 3, 4, 5])

In [30]:
print(i[0:2,0:2])

[[1 0]
 [0 1]]


<h3>Replacing elements</h3>

In [31]:
seq[2:6]=(1,55,66,77)
seq

array([ 0,  1,  1, 55, 66, 77,  6,  7,  8])

In [32]:
b[1:3,1:3] = ((2,2),(2,3))
b

array([[0, 0, 0],
       [0, 2, 2],
       [0, 2, 3]], dtype=int8)

<h3>Basic oprtations</h3>

In [33]:
print(seq+4) #adding 4 element wise
print()
print(c+b) #adding two matices

[ 4  5  5 59 70 81 10 11 12]

[[1 1 1]
 [1 3 3]
 [1 3 4]]


In [34]:
b*5 #element wise multiplication

array([[ 0,  0,  0],
       [ 0, 10, 10],
       [ 0, 10, 15]], dtype=int8)

In [35]:
print(b @ i) #matrix multiplication with @ symbol
print()
print(b.dot(c)) #matrix multiplication with dot function

[[0 0 0]
 [0 2 2]
 [0 2 3]]

[[0 0 0]
 [4 4 4]
 [5 5 5]]


<h3>Iterating through a numpy array</h3>

In [36]:
for x in i:
    print(x)

[1 0 0]
[0 1 0]
[0 0 1]


In [37]:
for x in i:
    for y in x:
        print(y)

1
0
0
0
1
0
0
0
1


## Matrices

In [38]:
# Finding the determinant of a matrix
print(np.linalg.det(c))
print(np.linalg.det(i))


0.0
1.0


In [39]:
# transpose
print(np.transpose(b))

[[0 0 0]
 [0 2 2]
 [0 2 3]]


In [40]:
# flatten
print(b.flatten())

[0 0 0 0 2 2 0 2 3]


In [41]:
#reshape
print(np.reshape(seq,(3,3)))

[[ 0  1  1]
 [55 66 77]
 [ 6  7  8]]


### Statistics

In [43]:
## max
stat = np.array([4,3,2,1])

## min
print(np.min(stat))

#max
print(np.max(stat))

#sum
print(np.sum(stat))

#average
print(np.average(stat))

1
4
10
2.5


In [47]:
mat = np.array(((1,2,3),(4,5,6)))
print(mat)
print(np.sum(mat, axis=0)) # axis zero means column wise
print(np.sum(mat, axis=1)) #axis one means row wise

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


### Rint, ciel, floor

In [4]:
ar = np.array((1.1,2.2,3.3,4.4,5.5,6.6))
print(np.rint(ar))
print(np.ceil(ar))
print(np.floor(ar))

[1. 2. 3. 4. 6. 7.]
[2. 3. 4. 5. 6. 7.]
[1. 2. 3. 4. 5. 6.]
